// src/lib/constants.js
export const TRANSACTION_STATES = [
  "INITIATED", "AWAITING_BUYER_STAKE", "AWAITING_SELLER_STAKE",
  "STAKED", "AWAITING_APPROVAL", "MILESTONE_APPROVED",
  "COMPLETED", "DISPUTED", "RESOLVED",
];
